### ISSUE TITLE
sentence_xlncet_config.json 오류

### ISSUE THREAD

**Issue by Yoojin730** [BM-K/Sentence-Embedding-Is-All-You-Need#4]
안녕하세요 BM-K님 !
작성해 주신 코드를 바탕으로
'''
bash get_model_checkpoint.sh
python SemanticSearch.py
'''
를 실행했습니다. 

FileNotFoundError: [Errno 2] No such file or directory: 
'./KoSBERT/Checkpoint/KoSBERT/kosbert-klue-bert-base/sentence_xlnet_config.json'

결과적으로 이와 같은 오류가 뜨는데 혹시 sentence_xlnet_config.json 파일은 어떻게 생성되는 것일까요?
편하실 때에 회신 주시면 감사드리겠습니다 :-)

**Comment by BM-K** [comment]
다음 이슈 참고 부탁드립니다 [[issue]](https://github.com/BM-K/KoSentenceBERT-SKT/issues/5#issuecomment-894985993).

이슈 해결이 안 될 시 다음 모델의 SemanticSearch.py 사용을 권해드립니다 [[KoSimCSE]](https://github.com/BM-K/Sentence-Embedding-Is-All-You-Need/tree/main/KoSimCSE#semantic-search).
