### ISSUE TITLE
DiffCSE 모델 학습 계획도 있으실까요? 

### ISSUE THREAD

**Issue by heartcored98** [BM-K/Sentence-Embedding-Is-All-You-Need#6]
안녕하세요. 저는 차량 문제 해결 플랫폼, 닥터차 서비스를 만드는 오토피디아에서 검색 서비스를 개발하고 있는 조재영이라고 합니다. 반갑습니다. 

최근에 한국어 문장 임베딩 모델이 절실히 필요한 상황이었는데, SimCSE를 KLUE Bert와 Roberta 모델에 적용한 레포지토리를 발견하게 되어서 무척 반가웠습니다. 저는 최근에 DiffCSE 방식도 알게 되었는데 혹시 이 방식에 대한 실험 결과도 추가하실 의향이 있으실까요? 

논문 구현체를 보니 SimCSE를 기반으로 되어 있는 것을 확인했습니다. 

- [DiffCSE 한국어 소개 자료](https://velog.io/@tobigs-nlp/DiffCSE-Difference-based-Contrastive-Learning-for-Sentence-Embeddings)
- [논문](https://aclanthology.org/2022.naacl-main.311.pdf)
- [원저자의 구현체](https://github.com/voidism/DiffCSE)

**Comment by heartcored98** [comment]
@BM-K 회신 감사드립니다 :) 
추후에 저희 쪽에서도 여력이 되어서 해당 모델을 학습할 계기가 생긴다면 PR 넣어볼 수 있도록 하겠습니다!

**Comment by BM-K** [comment]
KoDiffCSE 모델 학습 코드 및 성능을 공개하여 commit합니다 [[KoDiffCSE]](https://github.com/BM-K/KoDiffCSE).

Unsupervised 학습 방법이 계속 발전하여 supervised 성능을 얼른 따라가면 좋겠네요 (～￣▽￣)～.

**Comment by heartcored98** [comment]
@BM-K 오우 업데이트해주셨군요 ㅎㅎ 감사합니다!!
